[pytest]
markers =
    positive: positive test cases
    negative: negative test cases
    smoke: critical functionality checks
    regression: full regression test suite
    api: API test cases

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)s | %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S