XPATH_LOCATORS = {
    "home_link": "//a[text()='Home']",
    "about_button": "//button[text()='About']",
    "contacts_button": "//button[text()='Contacts']",
    "guest_login_button": "//button[text()='Guest log in']",
    "sign_in_button": "//button[text()='Sign In']",
    "sign_up_button": "//button[text()='Sign up']",
    "logo_link": "//a[@class='header_logo']",
    "logo_svg": "//a[@class='header_logo']/*[name()='svg']",
    "main_title": "//h1[text()='Do more!']",
    "main_description": "//p[contains(text(), 'With the help of the Hillel auto project')]",
    "instructions_image": "//img[@alt='Instructions']",
    "log_fuel_expenses_title": "//p[text()='Log fuel expenses']",
    "fuel_expenses_description": "//p[contains(text(), 'Keep track of your')]",
    "instructions_title": "//p[text()='Instructions and manuals']",
    "instructions_description": "//p[contains(text(), 'Watch over')]",
    "contacts_title": "//h2[text()='Contacts']",
    "hillel_website_link": "//a[text()='ithillel.ua']",
    "support_email_link": "//a[@href='mailto:developer@ithillel.ua']",
    "facebook_icon": "//a[contains(@href, 'facebook.com')]/span[contains(@class, 'icon-facebook')]",
    "telegram_icon": "//a[contains(@href, 't.me')]/span[contains(@class, 'icon-telegram')]",
    "youtube_icon": "//a[contains(@href, 'youtube.com')]/span[contains(@class, 'icon-youtube')]",
    "instagram_icon": "//a[contains(@href, 'instagram.com')]/span[contains(@class, 'icon-instagram')]",
    "linkedin_icon": "//a[contains(@href, 'linkedin.com')]/span[contains(@class, 'icon-linkedin')]",
    "copyright_text": "//p[contains(text(), '2021 Hillel IT school')]",
    "footer_description": "//p[contains(text(), 'Hillel auto developed')]"
}

CSS_LOCATORS = {
    "support_email_link": "a[href='mailto:developer@ithillel.ua']",
    "facebook_icon": "a[href*='facebook.com'] span[class*='icon-facebook']",
    "telegram_icon": "a[href*='t.me'] span[class*='icon-telegram']",
    "youtube_icon": "a[href*='youtube.com'] span[class*='icon-youtube']",
    "instagram_icon": "a[href*='instagram.com'] span[class*='icon-instagram']",
    "linkedin_icon": "a[href*='linkedin.com'] span[class*='icon-linkedin']",
    "header_logo": "a.header_logo svg",
    "home_link": "a.header-link[href='/']",
    "about_button": "button[appscrollto='aboutSection']",
    "contacts_button": "button[appscrollto='contactsSection']",
    "guest_login_button": "button.header-link.-guest",
    "sign_in_button": "button.header_signin",
    "sign_up_button": "button.hero-descriptor_btn",
    "hero_title": "h1.hero-descriptor_title",
    "hero_description": "p.hero-descriptor_descr",
    "fuel_expenses_image": "img[src*='info_1.jpg']",
    "fuel_expenses_title": "#aboutSection .col-lg-6:first-child p.about-block_title",
    "fuel_expenses_description": "#aboutSection .row > .col-lg-6:first-child p.about-block_descr",
    "instructions_image": "img[src*='info_2.jpg']",
    "instructions_title": "#aboutSection .row > .col-lg-6:nth-child(2) p.about-block_title",
    "instructions_description": "#aboutSection .row > .col-lg-6:nth-child(2) p.about-block_descr",
    "contacts_title": "#contactsSection h2",
    "copyright_text": "footer .footer_item.-left p:first-child",
    "footer_description": "footer .footer_item.-left p:nth-child(2)",
    "footer_logo": "a.footer_logo svg",
}
